CREATE TABLE [dbo].[Contacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,FirstName NVARCHAR(250) NOT NULL
	,LastName NVARCHAR(250) NOT NULL
	,Email NVARCHAR(250) NOT NULL
	,PhoneNumber VARCHAR(15) NOT NULL
	,[Status] BIT NOT NULL DEFAULT(1) 
)
